services:
  torch-worker1:
    image: aigendrug-cid-torch-worker
    container_name: torch-worker1
    networks:
      - aigendrug-cid-network
    volumes:
      - ~/aigendrug-cid-backend/ml-coordinator/.weights/:/app/weights/
      - ~/aigendrug-cid-backend/ml-coordinator/.csv/:/app/csv/
    expose:
      - "5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  torch-worker2:
    image: aigendrug-cid-torch-worker
    container_name: torch-worker2
    networks:
      - aigendrug-cid-network
    volumes:
      - ~/aigendrug-cid-backend/ml-coordinator/.weights/:/app/weights/
      - ~/aigendrug-cid-backend/ml-coordinator/.csv/:/app/csv/
    expose:
      - "5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  torch-worker3:
    image: aigendrug-cid-torch-worker
    container_name: torch-worker3
    networks:
      - aigendrug-cid-network
    volumes:
      - ~/aigendrug-cid-backend/ml-coordinator/.weights/:/app/weights/
      - ~/aigendrug-cid-backend/ml-coordinator/.csv/:/app/csv/
    expose:
      - "5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

networks:
  aigendrug-cid-network:
    external: true
